# Workflow to sync current repo with another one
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent action
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: adrianjost/files-sync-action@v1.0.1
      with:
        FILE_PATTERNS: |
          ^.*
        TARGET_REPOS: |
          lena-cms/lena-cms.github.io
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
